# version: "3.9"

services:
    api:
        build: .
        container_name: lms_api
        env_file:
            - .env
        expose:
            - '3000'

    nginx:
        image: nginx:latest
        container_name: lms_nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx-conf/nginx.conf:/etc/nginx-conf/nginx.conf:ro
        depends_on:
            - api
